### ISSUE TITLE
error building lukko on linux

### ISSUE THREAD

**Issue by ciez** [phadej/lukko#14]
build failed on Linux:
[lukko-build-fail.log](https://github.com/phadej/lukko/files/4251439/lukko-build-fail.log)

gcc --version
gcc (GCC) 9.2.0

**Comment by phadej** [comment]
Looks like you don't have `F_OFD_SETLKW` etc. macros defined. What kernel are you on?

If you have some non-standard one, you should disable ofd locking by turning `ofd-locking` flag off.

There might be some interaction with `_GNU_SOURCE` though, I'm not 100% sure.

**Comment by ciez** [comment]
the kernel version is 3.10.0-1062.12.1.el7.x86_64
found 
````
#  define F_OFD_SETLKW	38
#  define F_SETLKW	7
````

in a few header files

replacing F_OFD_SETLKW with F_SETLKW as suggested in the error message allowed lukko package to be built. Is this a viable solution?

ok, never mind. This does not block me.

**Comment by phadej** [comment]
![Screenshot from 2020-02-26 11-04-36](https://user-images.githubusercontent.com/51087/75329158-d83e1d00-5887-11ea-8cab-85f045e20d13.png)

**Comment by ciez** [comment]
> cabal: Failed to build lukko-0.1.1.3 (which is required by exe:cabal from
> cabal-install-3.4.0.0). 

is it possible to pass the ofd-locking flag to cabal when upgrading cabal-install?

can lukko be modified to check for F_OFD_SETLKW and the other OFD flags when building?
